version: "3"
services:
    walletapi:
      image: iw.api
      container_name: iw.api
      ports:
        - "5000:5000"
      environment:
        - DAPP_DID=did:ethr:rsk:0x1AC246974C1751a7FCA08ceAFf04Af0007f3bf8E
        - IW_DID=did:ethr:rsk:0xF3Fb96359A2586FD308aB1fe1B86BE3EA17b5F57
        - IW_VM=did:ethr:rsk:0xF3Fb96359A2586FD308aB1fe1B86BE3EA17b5F57#delegate-1
        - API_WALLET_USERNAME=test
        - API_WALLET_PWD=123456
        - SDK_API_URL=https://saas-qa.extrimian.com/services/sdk
        - API_URL=https://saas-qa.extrimian.com/services
        - DID_API_URL=https://saas-qa.extrimian.com/services/did
    iw:
      image: iw.front
      container_name: iw.front
      ports:
        - "4200:80"
      environment:
        - IW_FRONTEND_URL=https://identity-wallet.apps-qa.extrimian.com
      depends_on:
        - iw.api